spring.application.name=chat
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Datasource
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Batch
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Elasticsearch
spring.elasticsearch.uris=${SPRING_ELASTICSEARCH_URIS}

# JWT
spring.jwt.secret=${JWT_SECRET}

# External API
data.api.key=${DATA_API_KEY}

# OAuth2
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# Mail (SMTP)
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}

# Error Monitor SDK
error-monitor.server-url=${ERROR_MONITOR_SERVER_URL:http://localhost:8090}
error-monitor.project-id=airport-chat
error-monitor.api-key=${ERROR_MONITOR_API_KEY:proj_9cf6f2ceb0d34da0b894b2e259ba4096}
error-monitor.ignore-exceptions=NoResourceFoundException
error-monitor.ignore-urls=/error